[package]
name = "bevy_include_assets"
authors = ["Arc-blroth <45273859+Arc-blroth@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
version = "0.1.1"
edition = "2021"

[dependencies]
bevy = { version = "0.8", default-features = false, features = ["bevy_asset"] }
